### ISSUE TITLE
Testing Page Types: Gallery Page

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#369]
Create this page type, publish and review results

**Comment by teresasilva71** [comment]
There is a beige border around the thumbnails on the gallery pages:
![merrill moat gallery](https://user-images.githubusercontent.com/7795841/35874645-eddb127c-0b21-11e8-87a7-7704a62bea2b.jpg)
https://merrill-dev.ucsc.edu/programs/moat/index.html

**Comment by teresasilva71** [comment]
The gallery images aren't working either. They're no longer clickable to view larger image.

**Comment by knice** [comment]
I checked out the Merrill page linked above. It is a left navigation page with a screenshot as the banner. Because the screenshot is of a gallery page, it's a faux gallery. It totally fooled me though.

I've tested another gallery page, located in the Astro site: https://www.astro-dev.ucsc.edu/about/image-galleries/lick/

Everything looks OK, so I'm going to close this.
