### ISSUE TITLE
Bottom Row Blocks

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#407]
Block title case sensitive?
It looks like the titles of the blocks no longer default to capital letters.
So depending on how the blocks were edited, they can have both.
Is the upper/lower case intentional OR is it a bug and we want the block titles to be capitalized?
https://sociology-dev.ucsc.edu
![block naming](https://user-images.githubusercontent.com/7795841/37123298-8cbff602-2218-11e8-8ec8-da7c9ced7823.jpg)

**Comment by knice** [comment]
The correct style for the new look is that block titles will be lowercase. 

If a user put the added the title text to the block in uppercase it will stay uppercase (it was not necessary to do this, because we used to convert it to uppercase with CSS).

I'm adding a tag to this, "release-notes," so we can ask users to look at their blocks after launch.

**Comment by knice** [comment]
Making these standard case is one of the accessibility/readability changes in the stylesheet.
