### ISSUE TITLE
Funky Font?

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#410]
Testing something else in Dev, I came across this funky top-nav font from the home page
![funky font](https://user-images.githubusercontent.com/7795841/37292852-0e9292a2-25cf-11e8-909b-204d14d73459.jpg)
But, once you click into the site, the top-nav font looks like this (which is correct, right?):
![funky font 1](https://user-images.githubusercontent.com/7795841/37292972-50356158-25cf-11e8-9de0-38e58cd0ae40.jpg)

**Comment by knice** [comment]
Each sub-nav item is wrapped in a `<p>` tag. This is not standard. It looks like someone edited the nav in Word or something and then copied it back into WCMS. 

![screen-2018-03-12-83117](https://user-images.githubusercontent.com/36719/37293270-0dd69308-25d0-11e8-9123-a32cc0efeb40.png)

Removing the extra paragraph tags resolves the issue. This should be fixed in the nav block in WCMS.

![screen-2018-03-12-83305](https://user-images.githubusercontent.com/36719/37293304-22ad9768-25d0-11e8-9f6a-5641d23ef308.png)

**Comment by teresasilva71** [comment]
OK, so it's site-specific? Client needs to fix?

**Comment by knice** [comment]
Client needs to fix.
