### ISSUE TITLE
Images not working in IE

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#430]
See ticket INC0548287
Happening on all sites.

**Comment by knice** [comment]
Hey T, is that the correct incident number? I can’t find it in Service Now. Can you assign that ticket to me?

**Comment by knice** [comment]
This is resolved. Quite a tricky little error. It had to do with the script I put in place to remove custom styles from main navigation links. 

So the billboards in IE were only broken since earlier this week, when I implemented the script.

For-refresh your browser if you don't see it right away.

![bs_win10_ie_11 0 1](https://user-images.githubusercontent.com/36719/38433043-56479648-397e-11e8-9b5e-41ba0d601772.jpg)
![bs_win10_ie_11 0](https://user-images.githubusercontent.com/36719/38433044-566715a4-397e-11e8-9629-a41fe7dbe1a7.jpg)
